assert False, "Expected exception"
exit()
